name:  Build x86 and arm Image

env:
  VERSION: 0.10.0

on:
  pull_request:
    branches:
      - exc-*
      - develop
  push:
    branches:
      - ecx-*
      - develop

jobs:
  docker-image-production:
    if: startsWith(github.ref_name, vars.PRO_BRANCH)
    env:
      REGISTRY: ${{ vars.PRO_REGISTRY }}
    name: Build x86 and arm Image production
    runs-on:
      group: Default
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PRO_HARBOR_USERNAME }}
          password: ${{ secrets.PRO_HARBOR_TOKEN }}
      - name: Build & Push Docker image
        run: make package
  docker-image-develop:
    if: startsWith(github.ref_name, vars.DEV_BRANCH)
    env:
      REGISTRY: ${{ vars.DEV_REGISTRY }}
    name: Build x86 and arm Image develop
    runs-on:
      group: Default
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Print Harbor Username
        run: echo Harbor UserName：${{secrets.PRO_HARBOR_USERNAME}}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PRO_HARBOR_USERNAME }}
          password: ${{ secrets.PRO_HARBOR_TOKEN }}
      - name: Build & Push Docker image
        run: make package
